### ISSUE TITLE
gopy: fix need of GODEBUG=cgocheck=0 b/c of Cgo-rules

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#103]
we need to lift the need to export the environment variable `GODEBUG=cgocheck=0`, coming from the way we generate C extention modules (and pass Go values to python and back) and the stricter Cgo rules that were enforced starting with Go-1.6

**Comment by corona10** [comment]
Yeah, I am thinking about how to solve this issue. One of way might be generating Go-level wrapping layer. 

For example, if Go function returns `String`, I suggest that we should generate wrapping codes which return `C.string`.(`gengo.go` will do this?) And then CFFI backend generates python functions which call a wrapped Go function.

**Comment by sbinet** [comment]
the way I was envisionning to fix it was the following (inspired by `gomobile`):
- when transferring a Go value to python, only transfer an identifier (ie: a `uint64` id)
- associate that `id` with the `unsafe.Pointer` address of that value (into a `map[uint64]unsafe.Pointer`) to pin the address of that value (so the Go GC won't collect it while it's being used on the python side)
- the python world only sees these `id`s and sends them back

so the `Cgo` code for this Go func:
```go
func MyFunc(a, b int) (MyStruct, error) { ... }
```

would look like:
```go
//export MyFunc
func MyFunc(a, b int) int64 {
  v, err := pkg.MyFunc(a,b)
  if err != nil {
    cgopy_set_error(err)
    return -1
  }
  id := cgopy_add_ref(&v)
  return id
}
```

this will put some pressure on the GC (as every single value is now potentially on the heap), but that's the only way I see.

**Comment by corona10** [comment]
@sbinet It looks reasonable. I agree your way and I think that this is the way we should go. :)

**Comment by abourget** [comment]
Does it otherwise mean that our Go programs in the current form will crash the Python code unexpectedly at any time ?

**Comment by sbinet** [comment]
IIUC, this means the program as it is may break w/o notice with any new Go version upgrade.

**Comment by rcoreilly** [comment]
This may be completely off-base (I'm very new to this area), but what about restricting the domain of functions that can be supported to avoid this problem, while giving reasonable functionality from the python perspective, by relying to the greatest extent possible on PyObjects instead of pointers into Go memory?

Specifically, generate wrappers that take and return PyObject pointers and interface exclusively with those.  Thus, you never expose the Go internal objects in any way.  This means using exclusively pass-by-value and return-by-value function calls.  e.g., when you have a method taking a slice arg, it creates a copy of the PyObject list, and the return likewise creates a copy of whatever as a PyObject.  Obviously that will introduce a lot of overhead, but hopefully it might be possible to do some tricks to point into the PyObject list memory (for args), which I think should persist at least during the call out?

In addition, the @corona10 idea above could be made available as an explicit choice to create a python-side variable that refers to a Go-side object, using a map[string]unsafe.Pointer on the Go-side and having an explicit "global variable" name that you assign to that object.  This could be used to call methods on such objects -- the python side essentially just passes in the string name, you lookup the pointer on the Go side (probably need to also store something about the type on the Go side, or just a func that does the appropriate conversion from unsafe.Pointer), and then use that plus the other pass-by-value args etc.

It seems like all the PyObject conversion code is in there already?  this idea has been considered and discarded, or that was used prior to CFFI or something for the first Py2 version?

**Comment by rcoreilly** [comment]
submitted a PR with this fix and many others (if accepted, many outstanding issues can be closed).
