### ISSUE TITLE
gopy: a question for flag format

### ISSUE THREAD

**Issue by mingrammer** [go-python/gopy#124]
There are some options such as below:

```shell
Options:
  -lang="py2": python version to use for bindings (python2|py2|python3|py3)
  -output="": output directory for bindings
  -symbols=true: include symbols in output
```

Those options are formatted as `-[option]` form. And the names of that options have more than two letters, but, in traditional unix way, the `-` is used with single letter option like `-l` or `-o` and the multiple letters options have `--lang` form, with `--`.

So, I have a question for why do you use the `-` for multiple letters options. Are there some reasons?

**Comment by corona10** [comment]
@mingrammer 
Yeah, sounds reasonable. I never thought about this.
I agree with your opinion. But there might be some reason why single '-' is used for long letters.
@sbinet can answer about this. When he is back. (OOO until late July).

**Comment by mingrammer** [comment]
long letters is better :) (english is not easy for me)

**Comment by sbinet** [comment]
IIRC, the `flag` package is more Unixy than Linuxy and draws from BSD more than GNU/Linux in how options are handled.

_ie_ there is no short/long options like we have with GNU `getopt`.

people have complained about that (no short/long options), that's why there are many replacements for `flag`, _e.g._ https://github.com/ogier/pflag

I have grown accustomed to the way Go's `flag` package works and for simple command-line programs such as `gopy`, I don't think migrating to something else is warranted.

Feel free to reopen if you disagree (and motivate your disagreement :P).
