### ISSUE TITLE
suggestion for package  install to `fix the import bug`

### ISSUE THREAD

**Issue by zju3351689** [go-python/gopy#239]
suggestion for package  install to `fix the import bug`

with  ‘go build’  to produce hi.py go.py in the  `outputhi` path.

code need changed: 
in ‘go.py’
    `import _hi`     => from . import _hi
    `import go `    => from . import go
in ‘hi.py’
     `import _hi`     => from . import _hi
     `import hi`       => from . import hi
    `import go`      => from .  import go

then the PYTHONPATH could be use the `$PATH/lib/python3.7/site-packages/` not the  `$PATH/lib/python3.7/site-packages/outputhi`

**Comment by justinfx** [comment]
This would be great to fix. I started testing a project with gopy today and hit thag import issue straight away. Had to fix it with a hack to temporarily modify the `sys.path` before and after importing the package

**Comment by rcoreilly** [comment]
Happy to incorporate a PR on this but I don't think I have the bandwidth or domain knowledge to evaluate directly -- paths and python are out of my experties..

**Comment by justinfx** [comment]
This has actually also been a long standing issue across many tickets in the protocol buffers python/grpc code gen: https://github.com/protocolbuffers/protobuf/issues/1491
The same issue occurs in the generated python code regarding import statements and python3 using absolute imports instead of python2 relative imports.

I would be fine to look at working up a patch. But similar to the protobuf issue, I would like to hear an opinion as to whether it should be wholesale changed to `from . import go.py` or if it should be an option like `--import-package=<NAME>`:

```
# absolute
--import-package='mypackage.foo.py'
# relative
--import-package='.'
```

And if the flag were defined, it would end up generating `from <package> import go.py`.
Seeing as python2 is long deprecated and absolute imports are the default in python3, I would opt for making the flag default to "." but allowing some control over the value if needed, in cases where the files might be separated.
