### ISSUE TITLE
bind: support for nested slices

### ISSUE THREAD

**Issue by phil-mansfield** [go-python/gopy#56]
The package

```
package nested_slice

func NestedSlice(s [][]float64) {
}
```

fails with

```
$ go build && gopy bind --lang=py2 .
panic: could not look-up "[]float64"!


goroutine 1 [running]:
github.com/go-python/gopy/bind.(*symtab).addSliceType(0x8205c5100, 0x820617ea0, 0x882076cad8, 0x820666000, 0x882076caa8, 0x8205c6d80, 0x808, 0x8205c5160, 0x18, 0x8205c6f50, ...)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:483 +0xacc
github.com/go-python/gopy/bind.(*symtab).addType(0x8205c5100, 0x882076cad8, 0x820666000, 0x882076caa8, 0x8205c6d80)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:366 +0x2aa
github.com/go-python/gopy/bind.(*symtab).processTuple(0x8205c5100, 0x8205c4de0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:337 +0x149
github.com/go-python/gopy/bind.(*symtab).addSymbol(0x8205c5100, 0x882076c408, 0x820617f40)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/symtab.go:317 +0xceb
github.com/go-python/gopy/bind.(*Package).process(0x82063edc0, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:179 +0x26a4
github.com/go-python/gopy/bind.NewPackage(0x820617ea0, 0x820657880, 0x19, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/bind/package.go:44 +0x390
main.newPackageFrom(0x8205de0a8, 0x1, 0x1, 0x82063ec80, 0x820658000, 0x8205de0a8, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:197 +0x3bf
main.newPackage(0x7fff5fbffa5d, 0x1, 0x8205c0144, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/gen.go:167 +0x638
main.gopyRunCmdBind(0x820628a20, 0x8205c0330, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/go-python/gopy/cmd_bind.go:73 +0x4eb
github.com/gonuts/commander.(*Command).Dispatch(0x820628a20, 0x8205c0330, 0x1, 0x1, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:221 +0x7e2
github.com/gonuts/commander.(*Command).Dispatch(0x820628b40, 0x8205c0310, 0x3, 0x3, 0x0, 0x0)
    /Users/phil/code/go/src/github.com/gonuts/commander/commands.go:187 +0x1f9
main.main()
    /Users/phil/code/go/src/github.com/go-python/gopy/main.go:38 +0x1fe
```

**Comment by justinfx** [comment]
Curious if any progress has been made yet on this issue? I started trying to export some real production Go code to Python, and hit a number of the issues listed on the bug tracker ( #63 , #57, #18 ), including this one. 

Originally I had tried to simply bind the original library. I immediately hit some of the mentioned issues such as "unable to look up XYZ". So I started writing a separate package to wrap and export only the bits I wanted, in a way that managed to bind. The easiest way would have been to be able to use embedding to localize types I want. That didn't work so I started wrapping a pointer to the original library. That was working fine, with me delegating to the original lib. But I encountered the problem of nested slices. At that point, I stopped, since it seems I would be doing way too much pulling apart, converting, and rebuilding of internal data. 

I noticed this issue as well as a few others are self-assigned. Hoping to hear some updates! And thanks for the awesome work thus far!

**Comment by sbinet** [comment]
unfortunately, no, not much work.
note that most of the work is blocked by #58 : we need to port the generated code to use `bind/seq` for compatibility with `go-1.6`.
a WIP branch is available here: https://github.com/go-python/gopy/tree/bind-seq

I will have time to work on `gopy` next week, though :)

**Comment by justinfx** [comment]
Ah, thanks for the update on that! Looking forward to seeing your work once you get the time.

**Comment by rcoreilly** [comment]
for old version, closing
