### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by huakairuoxiangxi** [go-python/gopy#69]
go get github.com/go-python/gopy

error message
package golang.org/x/tools/go/types: unrecognized import path "golang.org/x/tools/go/types"
package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader"

**Comment by sbinet** [comment]
hum...
could you show the output of:

```sh
$ go env
$ go version
$ go get -u -v github.com/go-python/gopy
```

**Comment by huakairuoxiangxi** [comment]
the problem is china's GFW!!!

**Comment by huakairuoxiangxi** [comment]
due to china's GWF!!!  23333333

**Comment by sbinet** [comment]
Could you retry now from master?
I have pushed a change that doesn't require (IIRC) any 'x/tools/...' package which (I think) are blocked by the GWF (because of the redirect to go.Googlesource.com).

Worse comes to worst, you could still install the 'x/tools/...' packages manually from their github location ('x/tools' is 'github.com/golang/tools')

Let me know.
-s

**Comment by huakairuoxiangxi** [comment]
thanks,i use vpn install success.

**Comment by sbinet** [comment]
great.
